apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: i4rqechk5-go 
  janus-idp.io/tekton: i4rqechk5-go
  backstage.io/kubernetes-id: i4rqechk5-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: i4rqechk5-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml