apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: i4rqechk5-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-go:2ee567a643540a1219f35199ef475580b6a2a8a4@sha256:71e065004aa3c79214631e1067507f5441b1ce66a1fc08d6dad16495bb2b23fc
          name: container-image
